uraisg/media-library-azure

- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj.user
- internet-webapp/MediaLibrary.Internet.Web/Models/ComputerVisionModel.cs
- internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
Changes
**Main view**
Created simple form to upload image
**ImageUpload Controller**
1. Uploaded image converted into stream, upload to blob container and generate image URL
1. Metadata Extractor is used to extract time and coordinate from images
1. Cognitive Services - Computer Vision is used to extract list of tag
1. JSON generated, and upload to another container for indexing
> Internet api

- internet-webapp/MediaLibrary.Internet.Web/AppSettings.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj.user
- internet-webapp/MediaLibrary.Internet.Web/Startup.cs
- internet-webapp/MediaLibrary.Internet.Web/appsettings.Development.json
- internet-webapp/MediaLibrary.Internet.Web/appsettings.sample.json
Removed hard-coded values and made things configurable. See appsettings.sample.json
@guangying94
> Created app settings and made storage and api settings configurable

- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj.user
- internet-webapp/MediaLibrary.Internet.Web/Models/ComputerVisionModel.cs
- internet-webapp/MediaLibrary.Internet.Web/Startup.cs
- internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
- Modified processed json with additional field
- controller return views to index
- upload form is only visible after authentication - check claims on email
@raffertyuy  @khteo
> Modified processed json, with view based authorization

- internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
Add introductory text and call to action on home page for unauthenticated users.
> Refine landing page

- internet-webapp/MediaLibrary.Internet.Web/Background/ScheduledService.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/RetrieveController.cs
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj
- internet-webapp/MediaLibrary.Internet.Web/Startup.cs
- intranet-webapp/MediaLibrary.Intranet.Web/AppSettings.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Background/ScheduledService.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/HomeController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/MediaLibrary.Intranet.Web.csproj
- intranet-webapp/MediaLibrary.Intranet.Web/Models/ComputerVisionModel.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/ErrorViewModel.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/InternetIndexModel.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Program.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Startup.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Views/_ViewImports.cshtml
Added background job that retrieve index and images every 1 hour and store in separate storage account.
> background service that retrieve images every 1 hour.

- internet-webapp/MediaLibrary.Internet.Web/AppSettings.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/RetrieveController.cs
- internet-webapp/MediaLibrary.Internet.Web/Models/UploadFormModel.cs
- internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
- Added Basic auth to both APIs
- Modified controller to accept multiple images, and overlay with the same metadata
> Added basic auth to APIs, enabled upload multiple images.

- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj.user
- internet-webapp/MediaLibrary.Internet.Web/Properties/launchSettings.json
- intranet-webapp/MediaLibrary.Intranet.Web/MediaLibrary.Intranet.Web.csproj
- intranet-webapp/MediaLibrary.Intranet.Web/Properties/launchSettings.json
- Enable Razor runtime compilation
- Fix misleading and incorrect intranet launch profile name
> Changes to facilitate local development

- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj
- intranet-webapp/MediaLibrary.Intranet.Web/MediaLibrary.Intranet.Web.csproj
Fixes problem of Microsoft.CodeAnalysis library being deployed in non-debug configurations
> Reference Razor runtime compilation conditionally

- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/HomeController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/MediaItem.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/SearchData.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Home/Index.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/wwwroot/css/media.css
Allow for switching presentation of search results between list view and map view
> intranet-app: Add map layout

- internet-webapp/MediaLibrary.Internet.Web/AppSettings.cs
- internet-webapp/MediaLibrary.Internet.Web/Background/ScheduledService.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj
- internet-webapp/MediaLibrary.Internet.Web/Models/ComputerVisionModel.cs
- intranet-webapp/MediaLibrary.Intranet.Web/AppSettings.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Background/ScheduledService.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/HomeController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/WebApiController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/ComputerVisionModel.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/InternetIndexModel.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/MediaItem.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Home/Index.cshtml
Fixed - 
Added image compression
Added function to create thumbnail
Changed background job to every minute
> bug fixed, large image, generate thumbnail

- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/WebApiController.cs
> intranet: Updated WebApiController.cs to fix build error

- intranet-webapp/MediaLibrary.Intranet.Web/Views/Home/Index.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Shared/_Layout.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Shared/_LoginPartial.cshtml
- fix: intranet: Set default location for non geotagged images
- fix: intranet:  fix: intranet: Show display name instead of preferred username in nav header
- fix: intranet: Remove broken Privacy link in navbar
> Fix minor issues in intranet app

- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
Closes #56 
Cognitive Services APIs have a 4MB size limit for input images. Improve the algorithm used to fit image file size within the maximum limit. This happens in three stages:
1. If original image resolution exceeds 25MP, scale the image down to around 24MP
2. Repeatedly scale image dimensions by 95%, up to 10 iterations
3. Repeatedly lower JPEG quality from 80 to 50 in steps of 5
If at any point during the process the current image is less than 4MB in size, stop the process and return the current image.
Also fixes an infinite loop that could happen with the previous algorithm when it fails to generate a smaller image of acceptable file size.
> fix: Try harder to reduce image file size for image content analysis

- internet-webapp/MediaLibrary.Internet.Web/Models/UploadFormModel.cs
- internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
- internet-webapp/MediaLibrary.Internet.Web/assets/styles/site.scss
Provide better instructions to users on how to enter metadata
> feat: Add help texts to upload form

- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/MediaLibrary.Internet.Web.csproj
- internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
- internet-webapp/MediaLibrary.Internet.Web/assets/scripts/upload.js
- internet-webapp/MediaLibrary.Internet.Web/webpack.mix.js
Check file size, faster uploads, and clearer feedback message on success
> Upload UX improvements

- internet-webapp/MediaLibrary.Internet.Web/AppSettings.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/appsettings.sample.json
Makes sorting results by time more stable
> feat(internet): record time for date taken and date uploaded

- intranet-webapp/MediaLibrary.Intranet.Web/Services/MediaSearchService.cs
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/components/MediaList.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/components/SearchResultsView.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/slices/gallerySlice.js
> Update list view UI on Gallery page

- internet-webapp/MediaLibrary.Internet.Web/package-lock.json
- intranet-webapp/MediaLibrary.Intranet.Web/package-lock.json
> deps: update deps to resolve vulnerabilities

- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/GalleryController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/WebApiController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Gallery/Edit.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/edit.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/styles/site.scss
**Edit**
- efilers can now edit items that they uploaded as well
- the [new tags] textbox will clear after a tag is added
> Allow item authors to edit their items

- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/components/GalleryPage.js
Solves issue of results not showing after applying filters and page number exceeds number of new results
> fix(iz): Reset page number after applying new filters

- intranet-webapp/MediaLibrary.Intranet.Web/Views/Gallery/Edit.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Gallery/Item.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/item.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/styles/site.scss
-Adjust UI on edit and item page to improve UX
> feat(iz): Make UI/UX changes to item and edit pages

- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/WebApiController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/UserInfo.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Services/GraphService.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Startup.cs
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/DisplayName.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/edit.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/slices/gallerySlice.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/item.js
-Created service and class
-Created a API get method in controller
-Fetch API on galleryslice, item and edit JS file
> Display name with email

- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/WebApiController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/DisplayName.js
- intranet-webapp/MediaLibrary.Intranet.Web/package-lock.json
-Using query to fetch display name with email
-Fix display name not displaying any information if left empty
> Fix Query Issue

- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
Authorization fallback policy is already set in Startup.cs
> fix: Remove superfluous AuthorizeAttribute

- intranet-webapp/MediaLibrary.Intranet.Web/AppSettings.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/GalleryController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Controllers/WebApiController.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Services/ItemService.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Services/MediaSearchService.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Gallery/Item.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/appsettings.sample.json
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/item.js
This PR implements part of #53 relating to deletion of uploaded images.
- admins can delete any files
- item authors can delete their files, provided that the upload is within 24hours
> Add delete function and UI

- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/Views/Home/Index.cshtml
This PR improves upload processing based on testing feedback:
- Honour EXIF orientation when generating image thumbnail
- Allow HEIC file upload
> Improve image upload processing

- internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/ImageInput.js
Move image size to information above filepond
> Combine file upload prompt to single line

- internet-webapp/MediaLibrary.Internet.Web/Controllers/DraftController.cs
Also reindent and remove unnecessary usings
> style: Add comment to empty catch clause in DraftController

- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/components/MediaGrid.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/components/MediaList.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/components/SpatialFilter.js
- intranet-webapp/MediaLibrary.Intranet.Web/assets/scripts/gallery/slices/gallerySlice.js
- intranet-webapp/MediaLibrary.Intranet.Web/package-lock.json
- intranet-webapp/MediaLibrary.Intranet.Web/package.json
> Show details on lightbox

- internet-webapp/MediaLibrary.Internet.Api/ImageEntity.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/DraftController.cs
- internet-webapp/MediaLibrary.Internet.Web/Controllers/ImageUploadController.cs
- internet-webapp/MediaLibrary.Internet.Web/Models/ComputerVisionModel.cs
- internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/AllContext.js
- internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/PreviewUpdate.js
- internet-webapp/MediaLibrary.Internet.Web/assets/scripts/UploadPortal/components/Stepper.js
- intranet-webapp/MediaLibrary.Intranet.Web/Background/ScheduledService.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/InternetIndexModel.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Models/MediaItem.cs
> Add declaration before confirming uploads

- internet-webapp/MediaLibrary.Internet.Web/Configuration/SecurityHeadersExtensions.cs
- intranet-webapp/MediaLibrary.Intranet.Web/Views/Shared/_ValidationScriptsPartial.cshtml
- intranet-webapp/MediaLibrary.Intranet.Web/package-lock.json
- intranet-webapp/MediaLibrary.Intranet.Web/package.json
- intranet-webapp/MediaLibrary.Intranet.Web/webpack.mix.js
- Fix missing static map for geolocated images on internet web app (due to CSP)
- Clean up unused libraries in intranet web app
> Minor fixes and improvements
